container:
  image: node:latest
codeclimate_task:
  container:
    image: ruby:2.5-alpine
  env:
    CC_TEST_REPORTER_ID: 7574433e1beed630cb9a171c688bb9e010d5028f00f7218d6e845fe138c65168
  bundle_cache:
    folder: vendor/bundle
    fingerprint_script: sha256sum Gemfile.lock
    populate_script: bin/bundle install --jobs=$(nproc --ignore=1) --path=vendor/bundle
  codeclimate_cache:
    folder: vendor/codeclimate
    fingerprint_script: sha256sum vendor/codeclimate/test-reporter-latest-linux-amd64
    populate_script:
      - mkdir --parents vendor/codeclimate
      - curl --location https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 >
        vendor/codeclimate/test-reporter
      - chmod +x vendor/codeclimate/test-reporter
  code_coverage_script:
    - ./vendor/codeclimate/test-reporter before-build
    - bin/rake test:rspec
    - ./vendor/codeclimate/test-reporter after-build --exit-code $?
rspec_task:
  container:
    matrix:
      image: ruby:2.5-alpine
      image: ruby:2.4-alpine
      image: ruby:2.3-alpine
  bundle_cache:
    folder: vendor/bundle
    fingerprint_script: sha256sum Gemfile.lock
    populate_script: bin/bundle install --jobs=$(nproc --ignore=1) --path=vendor/bundle
  rspec_script: bin/rake test:rspec
