cache:
  directories:
  - vendor/bundle
git:
  depth: 1
notifications:
  webhooks:
  - https://webhooks.gitter.im/e/3a11f6fb1385c5cdb12b
before_cache: bin/bundle clean
jobs:
  include:
  - stage: Unit Tests
    name: Ruby 2.3 on Ubuntu 14.p0
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.3.4
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    install:
    - bin/bundle check || bin/bundle install
    script: bin/rake test:rspec
  - name: Ruby 2.4 with Code Climate on Ubuntu 14.04
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    env:
    - CC_TEST_REPORTER_ID=7574433e1beed630cb9a171c688bb9e010d5028f00f7218d6e845fe138c65168
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    install:
    - bin/bundle check || bin/bundle install
    before_script:
    - curl --location https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - bin/rake test:rspec
    after_script: "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - name: Ruby 2.5 on Ubuntu 14.04
    dist: trusty
    sudo: false
    language: ruby
    rvm: '2.5'
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:rspec
  - stage: Integration Tests on Ubuntu 14.04
    name: Terraform 0.11.4
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip
    - sha256sum terraform_0.11.4_linux_amd64.zip | grep 817be651ca41b999c09250a9fcade541a941afab41c0c663bd25529a4d5cfd31
    - unzip terraform_0.11.4_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.5
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
    - sha256sum terraform_0.11.5_linux_amd64.zip | grep 131c440263382c79c7f783b70ff35cd1d03eb31c44f7738d153d95a0b8436ac9
    - unzip terraform_0.11.5_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.6
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.6/terraform_0.11.6_linux_amd64.zip
    - sha256sum terraform_0.11.6_linux_amd64.zip | grep aed5c7388a3c54dc816986903d4dea32e182a002d746295e1016f6db741f472d
    - unzip terraform_0.11.6_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.7
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    - sha256sum terraform_0.11.7_linux_amd64.zip | grep 6b8ce67647a59b2a3f70199c304abca0ddec0e49fd060944c26f666298e23418
    - unzip terraform_0.11.7_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.8
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
    - sha256sum terraform_0.11.8_linux_amd64.zip | grep 84ccfb8e13b5fce63051294f787885b76a1fedef6bdbecf51c5e586c9e20c9b7
    - unzip terraform_0.11.8_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.9
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.9/terraform_0.11.9_linux_amd64.zip
    - sha256sum terraform_0.11.9_linux_amd64.zip | grep 5d674e7b83945c37f7f14d0e4f655787dad86ba15b26e185604aa0c3812394ab
    - unzip terraform_0.11.9_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.10
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    before_install:
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - curl --remote-name https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
    - sha256sum terraform_0.11.10_linux_amd64.zip | grep 43543a0e56e31b0952ea3623521917e060f2718ab06fe2b2d506cfaa14d54527
    - unzip terraform_0.11.10_linux_amd64.zip -d "$HOME"/bin
    script:
    - bin/rake test:kitchen:all
  - stage: Integration Tests on MacOS
    name: Terraform 0.11.4
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.4
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.5
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.5
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.6
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.6
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.7
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.7
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.8
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.8
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.9
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.9
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.10
    os: osx
    language: ruby
    rvm: 2.4.1
    addons:
      homebrew:
        packages:
        - terraform@0.11.10
    before_install:
    - bin/bundle config jobs $(expr $(sysctl -n hw.ncpu) - 1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    script:
    - bin/rake test:kitchen:all
  - stage: Integration Tests on Windows
    name: Terraform 0.11.4
    os: windows
    language: minimal
    before_install:
    - gem install bundler
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - choco install terraform --version=0.11.4
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.5
    os: windows
    language: minimal
    before_install:
    - gem install bundler
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - choco install terraform --version=0.11.5
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.6
    os: windows
    language: minimal
    before_install:
    - gem install bundler
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - choco install terraform --version=0.11.6
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.7
    os: windows
    language: minimal
    before_install:
    - gem install bundler
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - choco install terraform --version=0.11.7
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.8
    os: windows
    language: minimal
    before_install:
    - gem install bundler
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - choco install terraform --version=0.11.8
    script:
    - bin/rake test:kitchen:all
  - name: Terraform 0.11.9
    os: windows
    language: minimal
    before_install:
    - gem install bundler
    - bin/bundle config jobs $(nproc --ignore=1)
    - bin/bundle config path vendor/bundle
    - bin/bundle config retry 3
    - bin/bundle config without development
    install:
    - bin/bundle check || bin/bundle install
    - choco install terraform --version=0.11.9
    script:
    - bin/rake test:kitchen:all
  - stage: Deploy to RubyGems
    if: branch = master
    dist: trusty
    sudo: false
    language: ruby
    rvm: 2.4.1
    env:
    - secure: J5e3tkk2OmiHhVajoOosMF7OznL3D5jt2pQyTnZBAw4gJf9/GMx5w5eW6c5hEvszq03dvuVaUeZiyi07JQ6LjG1h8REA9YnBQbxNN9Dij5ptEtOFDV8M6fuAn2Uq388OZ9jTfw65m8hLjLYPK8jjKQIzf4B2ts0TitdsLXhNVOCIY+Cgtq0/vOgnexpphDdRWK/l6bkOnOumg8GMvV9eiOwaFzPmMWsyzuVZJ7JvowU2gxLPC0hmWWS4G7krSmOa+perUWy3qEa2DwWO9jwQ6KZCwSGYMhjvrbpEYoGKFlZbMdOMesfvmFoqB3xFNva6a6sFt6rdHzxtWn6DFFWz1EKIpsEgK/Pp7qTUY2+bbSBkeEuFJo66rjOlcIlIkNhLj/8T/uCtsM4Zkv4tRyIZWNaNeWmP4+GmCN9oPYYOP5M/AM8UEEePfW0z9d/RuzbDF9vEhZ/yE1068/sbblX/GnwdPBKZ2PKxpyCqAvlGWOWXSJP1kL2gcsjGcku8hbT2h1uJu17tkcn5YyVSzW2XFotO+GJl9Kn3rf6fVD+24jrj1qa4eud8y82/iGyHa/DbQd7a8BjaA/amCI0ZujwbZxnaVFMW8GQCmPP+TXuwbj7Al2DXEGFhdkwGQnzz5bJ0pDjdqxMd27jYgOn+qYQvbFNdcJm/DnGbJdeirZyjMG4=
    install: true
    script: true
    before_cache: true
    before_deploy:
    - openssl aes-256-cbc -K $rubygems_private_key_password -in certs/gem-private_key.pem.enc
      -out certs/gem-private_key.pem -d
    - gem cert --add certs/gem-public_cert.pem
    deploy:
      provider: rubygems
      api_key:
        secure: ja3412pmLoTwj/oyEacaMxfQbCc3YWHvHst7X01HNyTlhL1aVp8zAjmbS9C/QtGc6PF0SZCk6ZxsQW0Ux0VCMBszGRu8CpyUYdUm94N66KDtMJtmlNpiXwgCFhUVe87tsV13FrwXlpzXXOoa+T6xNhkbSaiELUJLnFDxSCPTrWSxabVHdbocs4tIperMVrKedlW2+MdNXqm4K8zEDkR67czxaEs8pndV9V7Dpr4RgMjipxrFbARefNWm+FPHVlkt25Z90m66muxvscH1w1zqlneiNRAoudFIev7dtO1OxZ6OwO7v27kFG9LSctn4hPbSyASOdRewqUQ446nJwXrm0W52vIpItC1Dx2l5oQ+Dc4SsCA4D6BaA2o+SWIMDkZE7rg/oRIfiOveuQ9cDk2sSr4cM+E0sPZt1XaaKjwmG7PsLvLa6hzwmvITRNpDf8a4eglfuipa9yHahqzfwt2M6o9GV8sNXzHuw6bsDjE5/EPZqDnVmlbdJfoR3YEcc8Wt/k8J9rPDsNu8YjBKf7LU932evaJjASvv7nD++d8Kj/2ENeq6xOVWwt1tYSESSj33lfY+oyGSZ8KsVjOLyCXjN6pMUIFm4r9eRLcA4RmdU7b5b9zvrYUfNle85tMSyCSDpGP8RlgP6sxctKOUUp7w1VkagLY1ZJd9or60u4KSPQWE=
      gem: kitchen-terraform
      on:
        repo: newcontext-oss/kitchen-terraform
        tags: true
      skip_cleanup: true
