cache:
  directories:
    - vendor/bundle
    - vendor/cache
notifications:
  webhooks: 
    - https://webhooks.gitter.im/e/3a11f6fb1385c5cdb12b
before_cache: bin/bundle clean
jobs:
  include:
    - stage: "Unit Tests"
      os: linux
      dist: trusty
      sudo: false
      language: ruby
      name: "Ruby 2.3"
      rvm: '2.3'
      before_install:
        - gem --version
        - bundle --version
        - curl --version
      script: bin/rake test:rspec
    - name: "Ruby 2.4"
      rvm: '2.4'
    - name: "Ruby 2.5 with Code Climate"
      rvm: '2.5'
      env:
        - CC_TEST_REPORTER_ID=7574433e1beed630cb9a171c688bb9e010d5028f00f7218d6e845fe138c65168
      before_script:
        - curl --location https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - './cc-test-reporter before-build'
      script:
        - bin/rake test:rspec
      after_script: './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
    - stage: "Integration Tests on Linux"
      os: linux
      dist: trusty
      sudo: false
      language: ruby
      rvm: '2.5'
      before_install:
        - gem --version
        - bundle --version
        - curl --version
        - sha256sum --version
        - unzip -v        
      install:
        - bin/bundle install --binstubs --jobs=$(nproc --ignore=1) --path=vendor/bundle --retry=3 --without=development
        - curl --remote-name 
          https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_SHA256SUMS
        - curl --remote-name 
          https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
        - sha256sum --check terraform_"$TERRAFORM_VERSION"_SHA256SUMS
        - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip -d bin
      script:
        - 'PATH=bin:$PATH bin/rake test:kitchen:all'
      name: "Terraform 0.11.4"
      env:
        - TERRAFORM_VERSION=0.11.4
    - name: "Terraform 0.11.5"
      env:
        - TERRAFORM_VERSION=0.11.5
    - name: "Terraform 0.11.6"
      env:
        - TERRAFORM_VERSION=0.11.6
    - name: "Terraform 0.11.7"
      env:
        - TERRAFORM_VERSION=0.11.7
    - name: "Terraform 0.11.8"
      env:
        - TERRAFORM_VERSION=0.11.8
    - name: "Terraform 0.11.9"
      env:
        - TERRAFORM_VERSION=0.11.9
    - name: "Terraform 0.11.10"
      env:
        - TERRAFORM_VERSION=0.11.10
    - stage: "Integration Tests on MacOS"
      os: osx
      osx_image: xcode10
      before_install:
        - gem --version
        - bundle --version
        - curl --version
        - sha256sum --version
        - unzip -v
      install:
        - bin/bundle install --binstubs --jobs=$(nproc --ignore=1) --path=vendor/bundle --retry=3 --without=development
        - curl --remote-name
          https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_SHA256SUMS
        - curl --remote-name
          https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_darwin_amd64.zip
        - sha256sum --check terraform_"$TERRAFORM_VERSION"_SHA256SUMS
        - unzip terraform_"$TERRAFORM_VERSION"_darwin_amd64.zip -d bin
      script:
        - 'PATH=bin:$PATH bin/rake test:kitchen:all'
      name: "Terraform 0.11.4"
      env:
        - TERRAFORM_VERSION=0.11.4
    - name: "Terraform 0.11.5"
      env:
        - TERRAFORM_VERSION=0.11.5
    - name: "Terraform 0.11.6"
      env:
        - TERRAFORM_VERSION=0.11.6
    - name: "Terraform 0.11.7"
      env:
        - TERRAFORM_VERSION=0.11.7
    - name: "Terraform 0.11.8"
      env:
        - TERRAFORM_VERSION=0.11.8
    - name: "Terraform 0.11.9"
      env:
        - TERRAFORM_VERSION=0.11.9
    - name: "Terraform 0.11.10"
      env:
        - TERRAFORM_VERSION=0.11.10
    - stage: "Integration Tests on Windows"
      os: windows
      language: shell
      install:
        - bin/bundle install --binstubs --jobs=$(nproc --ignore=1) --path=vendor/bundle --retry=3 --without=development
        - curl --remote-name
          https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_SHA256SUMS
        - curl --remote-name
          https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_windows_amd64.zip
        - sha256sum --check terraform_"$TERRAFORM_VERSION"_SHA256SUMS
        - unzip terraform_"$TERRAFORM_VERSION"_windows_amd64.zip -d bin
      script:
        - 'PATH=bin:$PATH bin/rake test:kitchen:all'
      name: "Terraform 0.11.4"
      env:
        - TERRAFORM_VERSION=0.11.4
    - name: "Terraform 0.11.5"
      env:
        - TERRAFORM_VERSION=0.11.5
    - name: "Terraform 0.11.6"
      env:
        - TERRAFORM_VERSION=0.11.6
    - name: "Terraform 0.11.7"
      env:
        - TERRAFORM_VERSION=0.11.7
    - name: "Terraform 0.11.8"
      env:
        - TERRAFORM_VERSION=0.11.8
    - name: "Terraform 0.11.9"
      env:
        - TERRAFORM_VERSION=0.11.9
    - name: "Terraform 0.11.10"
      env:
        - TERRAFORM_VERSION=0.11.10
    - stage: "Deploy to RubyGems"
      if: branch = master
      os: linux
      dist: trusty
      sudo: false
      language: ruby
      rvm: '2.5'
      before_install:
        - gem --version
      install: true
      script: true
      before_cache: true
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_8619fb193385_key -iv $encrypted_8619fb193385_iv
          -in certs/gem-private_key.pem.enc -out certs/gem-private_key.pem -d
        - gem cert --add certs/gem-public_cert.pem
      deploy:
        provider: rubygems
        api_key:
          secure: 'ja3412pmLoTwj/oyEacaMxfQbCc3YWHvHst7X01HNyTlhL1aVp8zAjmbS9C/QtGc6PF0SZCk6ZxsQW0Ux0VCMBszGRu8CpyUYdUm94N66KDtMJtmlNpiXwgCFhUVe87tsV13FrwXlpzXXOoa+T6xNhkbSaiELUJLnFDxSCPTrWSxabVHdbocs4tIperMVrKedlW2+MdNXqm4K8zEDkR67czxaEs8pndV9V7Dpr4RgMjipxrFbARefNWm+FPHVlkt25Z90m66muxvscH1w1zqlneiNRAoudFIev7dtO1OxZ6OwO7v27kFG9LSctn4hPbSyASOdRewqUQ446nJwXrm0W52vIpItC1Dx2l5oQ+Dc4SsCA4D6BaA2o+SWIMDkZE7rg/oRIfiOveuQ9cDk2sSr4cM+E0sPZt1XaaKjwmG7PsLvLa6hzwmvITRNpDf8a4eglfuipa9yHahqzfwt2M6o9GV8sNXzHuw6bsDjE5/EPZqDnVmlbdJfoR3YEcc8Wt/k8J9rPDsNu8YjBKf7LU932evaJjASvv7nD++d8Kj/2ENeq6xOVWwt1tYSESSj33lfY+oyGSZ8KsVjOLyCXjN6pMUIFm4r9eRLcA4RmdU7b5b9zvrYUfNle85tMSyCSDpGP8RlgP6sxctKOUUp7w1VkagLY1ZJd9or60u4KSPQWE='
        gem: kitchen-terraform
        on:
          repo: newcontext-oss/kitchen-terraform
          tags: true
        skip_cleanup: true
